### ISSUE TITLE
Sample?

### ISSUE THREAD

**Issue by Lir10** [danielgindi/java-httprequest#1]
Looks a great library 

Any sample would be helpful 
Thanks!

**Comment by danielgindi** [comment]
It's a good point :-)
Unfortunately I haven't had the time yet to generate sample code in the README...

But try to use it naturally:

```
HttpRequest.postRequest(url)
  .setContentType(HttpRequest.ContentType.JSON)
  .addHeader("MyHeader", "Value")
  .setRequestBody("{\"key\": \"value\"}")
  .getResponseAsync(...)
```

Of course there are many features like automatically handling multipart encoding, setRequestBody from stream, adding a part from stream, adding a part from file, etc. without filling up the RAM.

If you write down some use cases - I can create samples for those and add to the README :)

**Comment by Lir10** [comment]
Thanks i will try that !
